name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: printf检测器
      id: printf
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: printf检测器
        setup-command: ''
        command: make test
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PRINTF_RESULTS: "${{steps.printf.outputs.result}}"
      with:
        runners: printf
